// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4IFiRTsjQK03kMEVB-vdTqlzEwm8myl4',
    appId: '1:481348685498:web:4129ff49099dee2b423c83',
    messagingSenderId: '481348685498',
    projectId: 'reportya-tesis',
    authDomain: 'reportya-tesis.firebaseapp.com',
    storageBucket: 'reportya-tesis.appspot.com',
    measurementId: 'G-Q17NBNWMQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBH8U7Qw-80t6tHY8n1xrR9ncHg0zZX4M',
    appId: '1:481348685498:android:5b71fbafdb7862fa423c83',
    messagingSenderId: '481348685498',
    projectId: 'reportya-tesis',
    storageBucket: 'reportya-tesis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLoygTreALXE6zEeQgzsWigXaaQZSw-mQ',
    appId: '1:481348685498:ios:862206e4aca85a07423c83',
    messagingSenderId: '481348685498',
    projectId: 'reportya-tesis',
    storageBucket: 'reportya-tesis.appspot.com',
    iosBundleId: 'com.codigocorrecto.reportya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLoygTreALXE6zEeQgzsWigXaaQZSw-mQ',
    appId: '1:481348685498:ios:862206e4aca85a07423c83',
    messagingSenderId: '481348685498',
    projectId: 'reportya-tesis',
    storageBucket: 'reportya-tesis.appspot.com',
    iosBundleId: 'com.codigocorrecto.reportya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4IFiRTsjQK03kMEVB-vdTqlzEwm8myl4',
    appId: '1:481348685498:web:579a66e3d829cd4a423c83',
    messagingSenderId: '481348685498',
    projectId: 'reportya-tesis',
    authDomain: 'reportya-tesis.firebaseapp.com',
    storageBucket: 'reportya-tesis.appspot.com',
    measurementId: 'G-KC8WQ777B1',
  );
}
